### ISSUE TITLE
Ejemplo

### ISSUE THREAD

**Issue by jorgesarabia** [jorgesarabia/ejemplo_fabricas#1]
### Tasks to perform
- [ ] Finish my changes
- [ ] Finish my changes
- [ ] Open a pull request

### Another
- [ ] Push my commits to GitHub
